In [1]:
import sys
import pandas as pd
import sqlite3

print(sys.executable)
print(pd.__version__)
print(sqlite3.sqlite_version)

c:\Users\Nestor\AppData\Local\Programs\Python\Python313\python.exe
2.3.0
3.45.3

In [2]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv("../data/spotify_clean.csv")
conn = sqlite3.connect("../data/spotify.db")
df.to_sql('tracks', conn, if_exists='replace', index=False)
|

SyntaxError: invalid syntax (4170361898.py, line 4)

In [4]:
df = pd.read_csv("../data/spotify_clean.csv")
conn = sqlite3.connect("../data/spotify.db")
df.to_sql('tracks', conn, if_exists='replace', index=False)

113105

In [6]:
pd.read_sql("""
    SELECT track_genre,
           ROUND(AVG(popularity), 1) AS avg_popularity,
           COUNT(*) AS track_count
    FROM tracks
    GROUP BY track_genre
    ORDER BY avg_popularity DESC
    LIMIT 10
""", conn)

  track_genre  avg_popularity  track_count
0    pop-film            59.3          998
1       k-pop            57.0          997
2       chill            53.8          998
3         sad            52.4         1000
4      grunge            49.6          998
5      indian            49.5          998
6       anime            48.8          998
7         pop            48.2          986
8         emo            48.1         1000
9   sertanejo            47.9         1000

In [7]:
pd.read_sql("""
    SELECT explicit,
           ROUND(AVG(popularity), 1) AS avg_popularity,
           COUNT(*) AS track_count
    FROM tracks
    GROUP BY explicit
""", conn)

   explicit  avg_popularity  track_count
0         0            33.1       103416
1         1            36.6         9689

In [8]:
pd.read_sql("""
    SELECT key, mode,
           ROUND(AVG(popularity), 1) AS avg_popularity,
           COUNT(*) AS track_count
    FROM tracks
    GROUP BY key, mode
    ORDER BY avg_popularity DESC
    LIMIT 10
""", conn)

   key  mode  avg_popularity  track_count
0    4     1            36.2         4257
1    1     0            35.0         3577
2    2     0            34.8         2553
3    6     0            34.7         3787
4    0     0            34.6         2834
5    2     1            34.5         8994
6    8     0            34.5         1906
7   11     1            34.4         4112
8    3     1            34.1         2202
9    5     0            34.0         3990

In [9]:
pd.read_sql("""
    SELECT track_name, artists, track_genre, popularity
    FROM tracks
    ORDER BY popularity DESC
    LIMIT 10
""", conn)

,track_name,artists,track_genre,popularity
0,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,dance,100
1,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,pop,100
2,"Quevedo: Bzrp Music Sessions, Vol. 52",Bizarrap;Quevedo,hip-hop,99
3,I'm Good (Blue),David Guetta;Bebe Rexha,dance,98
4,I'm Good (Blue),David Guetta;Bebe Rexha,edm,98
5,La Bachata,Manuel Turizo,latin,98
6,La Bachata,Manuel Turizo,latino,98
7,I'm Good (Blue),David Guetta;Bebe Rexha,pop,98
8,La Bachata,Manuel Turizo,reggae,98
9,La Bachata,Manuel Turizo,reggaeton,98

In [10]:
pd.read_sql("""
    SELECT DISTINCT(track_name), artists, track_genre, popularity
    FROM tracks
    ORDER BY popularity DESC
    LIMIT 10
""", conn)

,track_name,artists,track_genre,popularity
0,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,dance,100
1,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,pop,100
2,"Quevedo: Bzrp Music Sessions, Vol. 52",Bizarrap;Quevedo,hip-hop,99
3,I'm Good (Blue),David Guetta;Bebe Rexha,dance,98
4,I'm Good (Blue),David Guetta;Bebe Rexha,edm,98
5,La Bachata,Manuel Turizo,latin,98
6,La Bachata,Manuel Turizo,latino,98
7,I'm Good (Blue),David Guetta;Bebe Rexha,pop,98
8,La Bachata,Manuel Turizo,reggae,98
9,La Bachata,Manuel Turizo,reggaeton,98

In [11]:
pd.read_sql("""
    SELECT track_name, artists, track_genre, popularity
    FROM tracks
    GROUP BY track_name
    ORDER BY popularity DESC
    LIMIT 10
""", conn)

,track_name,artists,track_genre,popularity
0,Unholy (feat. Kim Petras),Sam Smith;Kim Petras,dance,100
1,"Quevedo: Bzrp Music Sessions, Vol. 52",Bizarrap;Quevedo,hip-hop,99
2,La Bachata,Manuel Turizo,latin,98
3,I'm Good (Blue),David Guetta;Bebe Rexha,dance,98
4,Tití Me Preguntó,Bad Bunny,latin,97
5,Me Porto Bonito,Bad Bunny;Chencho Corleone,latin,97
6,I Ain't Worried,OneRepublic,piano,96
7,Efecto,Bad Bunny,latin,96
8,Ojitos Lindos,Bad Bunny;Bomba Estéreo,latin,95
9,Moscow Mule,Bad Bunny,latin,94

In [13]:
pd.read_sql("""
    SELECT AVG(popularity) as avg_popularity
    FROM tracks
    WHERE track_genre = 'rock'
""", conn)

   avg_popularity
0          19.001